woowacourse-teams/2023-map-befine

backend/deploy.sh

[BE] 개발 서버 배포 자동화 쉘 스크립트 작성 #81 

---

backend/build.gradle
backend/src/main/resources/application-dev.yml
backend/src/main/resources/application.properties
backend/src/main/resources/application.yml

개발 서버 데이터베이스, 서버 구성 파일
- DB 환경을 H2에서 MySQL로 이관
- 개발 서버 구성 파일 수정
- DDL-auto 옵션 변경 : 이미 테이블을 생성한 상태이기 때문에 none 옵션으로 변경하였습니다.
#131 
https://meatsby.github.io/posts/aws-ec2-spring-to-mysql/

[BE] 개발서버 DB H2에서 MySQL로 이관

---

backend/src/main/java/com/mapbefine/mapbefine/controller/TopicController.java
backend/src/main/java/com/mapbefine/mapbefine/repository/TopicRepository.java
backend/src/main/java/com/mapbefine/mapbefine/service/TopicQueryService.java

- TopicController
- TopicQueryService
- TopicRepository
- 토픽 다건 상세 조회를 위한 API 구현
#141 
closed #141

[BE] 토픽 다건 상세조회 API 구현

---

frontend/src/components/TopicInfo/index.tsx
frontend/src/pages/NewPin.tsx
frontend/src/pages/SelectedTopic.tsx

<co-author: @kpeel5839> ❤️
같이보기, 핀 생성과 관련된 로직 (라우터 포함)
hash Map 사용
#191

[FE]Fix#191 같이보기 상태에서 핀 추가시 발생하는 오류 수정

---

frontend/src/components/Layout/index.tsx
frontend/src/components/Toast/index.tsx
frontend/src/components/TopicInfo/index.tsx
frontend/src/components/common/Text/index.ts
frontend/src/constants/index.ts
frontend/src/context/ToastContext.tsx
frontend/src/hooks/useToast.ts
frontend/src/pages/NewPin.tsx
frontend/src/pages/NewTopic.tsx
frontend/src/pages/PinDetail.tsx
frontend/src/pages/SelectedTopic.tsx
frontend/src/types/Toast.ts

기존 alert를 toast 알림으로 대체합니다. 따라서 Toast 컴포넌트를 구현하고 필요한 것들 (context, custom hook 등) 을 추가합니다.
추상화 해뒀습니다. 따라서 Toast 필요하신 곳 가셔서
```jsx
const { showToast } = useToast();
showToast(type, message);
// 매개변수 타입
type: 'info' | 'warn' | 'error'; // Toast 배경 색 다름여
message: string // Toast 안에 보여줄 문구
```
위와 같이 사용하시면 끝 Super Easy 하죠?
* 대신 showToast 하는 버튼 연타하면 애니메이션 깨져요. 연타할 상황이 딱히 없어보여서 문제 생기면 그 때 대응하겠습니다. (애니메이션 로직 다 갈아야해서..)
https://github.com/woowacourse-teams/2023-map-befine/assets/89172499/41f05bf4-549b-4ef0-96c4-153c5d38f4ae
close #205

[FE]Feature/#205 Toast 컴포넌트 구현 및 기존 alert 대체

---

.github/workflows/be-merge-dev.yml
.github/workflows/be-merge-prod.yml
.github/workflows/be-pull-request.yml

백엔드 workflow 전체
workflow에 테스트 실행 시 쓰이는 환경변수 설정을 추가했습니다.
자세한 내용은 #272 참조 부탁드립니다.
이렇게 설정해주어야 하는 값이 많아지거나, 관리가 불편해진다면 서브모듈 도입 고려해볼 만한 것 같아요!
지금 이 값들은 수정할 일이 없고 새로운 시크릿키로 변경해주어도 문제가 없어서 일단 적용했습니다.
workflow 작동 확인은 #271  에서 완료했습니다.
소셜 로그인 #255 PR merge 전에 merge되어야 합니다.
closed #272

[BE] env/#272 CI/CD 테스트를 위한 환경변수 설정 추가

---

frontend/src/components/Layout/index.tsx
frontend/src/components/MyInfoContainer/MyInfoList/index.tsx
frontend/src/pages/Profile.tsx

[FE] fix: 버그 일괄 수정

---

frontend/src/apis/getApi.ts
frontend/src/components/MyInfo/index.tsx
frontend/src/components/common/CheckBox/index.tsx
frontend/src/pages/NewTopic.tsx
frontend/src/pages/PinDetail.tsx

fix: 에러 수정

---

frontend/src/components/Layout/Logo.tsx
frontend/src/components/Layout/Navbar.tsx
frontend/src/components/Map/index.tsx
frontend/src/components/Modal/index.tsx
frontend/src/components/Toast/index.tsx
frontend/src/components/TopicCard/index.tsx
frontend/src/components/TopicInfo/index.tsx
frontend/src/components/TopicListContainer/index.tsx
frontend/src/components/common/CheckBox/index.tsx
frontend/src/hooks/useKeyDown.ts
frontend/src/pages/NewTopic.tsx

웹 접근성 적용
핵심기능(토픽 추가, 핀 추가, 뽑아오기)에 웹 접근성 적용
close #325

[FE] feature/#325 웹 접근성 적용

---

backend/src/main/java/com/mapbefine/mapbefine/common/interceptor/AuthInterceptor.java
backend/src/main/resources/application-dev.yml
backend/src/main/resources/application-prod.yml
backend/src/main/resources/logback-spring.xml
backend/src/test/java/com/mapbefine/mapbefine/topic/TopicIntegrationTest.java

- log-back.xml
- AuthInterceptor
- 로그인 버그로 인한 인터셉터 수정 및 로그백 일부 수정

[BE] hotfix/log 로그인 버그로 인한 인터셉터 수정 및 로그백 일부 수정

---

backend/src/main/java/com/mapbefine/mapbefine/member/domain/Member.java
backend/src/main/java/com/mapbefine/mapbefine/oauth/domain/OauthMember.java
backend/src/main/java/com/mapbefine/mapbefine/oauth/domain/kakao/dto/KakaoMemberResponse.java
backend/src/test/java/com/mapbefine/mapbefine/oauth/application/OauthServiceTest.java
backend/src/test/java/com/mapbefine/mapbefine/oauth/domain/OauthMemberTest.java

OauthMember 관련
랜덤 닉네임에 고정 문자열을 사용함으로 인해 해당 사용자를 식별하기 어려워서,  
닉네임 수정 기능 적용 전까지 카카오 닉네임+UUID를 랜덤 닉네임으로 사용하도록 수정했습니다.
카카오 닉네임이 13자 초과일 경우 기본 랜덤 닉네임(모험가+UUID)을 부여합니다.

[BE] feature/nickname 랜덤 닉네임에 고정 문자열 대신 카카오 닉네임 사용

---

backend/src/main/java/com/mapbefine/mapbefine/atlas/exception/AtlasErrorCode.java
backend/src/main/java/com/mapbefine/mapbefine/atlas/exception/AtlasException.java
backend/src/main/java/com/mapbefine/mapbefine/auth/domain/member/User.java
backend/src/main/java/com/mapbefine/mapbefine/bookmark/application/BookmarkCommandService.java
backend/src/main/java/com/mapbefine/mapbefine/bookmark/exception/BookmarkException.java
backend/src/main/java/com/mapbefine/mapbefine/common/GlobalExceptionHandler.java
backend/src/main/java/com/mapbefine/mapbefine/common/exception/BadRequestException.java
backend/src/main/java/com/mapbefine/mapbefine/common/exception/ConflictException.java
backend/src/main/java/com/mapbefine/mapbefine/common/exception/ErrorCode.java
backend/src/main/java/com/mapbefine/mapbefine/common/exception/ForbiddenException.java
backend/src/main/java/com/mapbefine/mapbefine/common/exception/GlobalException.java
backend/src/main/java/com/mapbefine/mapbefine/common/exception/NotFoundException.java
backend/src/main/java/com/mapbefine/mapbefine/common/exception/UnauthorizedException.java
backend/src/main/java/com/mapbefine/mapbefine/common/exception/dto/ErrorResponse.java
backend/src/main/java/com/mapbefine/mapbefine/location/exception/LocationException.java
backend/src/main/java/com/mapbefine/mapbefine/member/application/MemberQueryService.java
backend/src/main/java/com/mapbefine/mapbefine/member/exception/MemberException.java
backend/src/main/java/com/mapbefine/mapbefine/oauth/domain/AuthCodeRequestUrlProviderComposite.java
backend/src/main/java/com/mapbefine/mapbefine/oauth/domain/OauthMemberClientComposite.java
backend/src/main/java/com/mapbefine/mapbefine/oauth/exception/OathException.java
backend/src/main/java/com/mapbefine/mapbefine/permission/application/PermissionCommandService.java
backend/src/main/java/com/mapbefine/mapbefine/permission/application/PermissionQueryService.java
backend/src/main/java/com/mapbefine/mapbefine/permission/exception/PermissionException.java
backend/src/main/java/com/mapbefine/mapbefine/pin/application/PinQueryService.java
backend/src/main/java/com/mapbefine/mapbefine/pin/exception/PinException.java
backend/src/main/java/com/mapbefine/mapbefine/topic/application/TopicQueryService.java
backend/src/main/java/com/mapbefine/mapbefine/topic/exception/TopicException.java

[BE] hotfix/auth member

---

.github/workflows/fe-pull-request.yml
frontend/cypress/e2e/mapbefine.cy.ts

* develop-FE 브랜치 분리
* 기존에 main hotfixes 작업 내용 충돌 해결 및 동기화
* cypress 테스트 자동화가 잘 되는지 확인이 필요합니다. 이전에 develop 에서 작업할 당시 마지막 변경사항에 대해서 확인하지 않았던 걸로 기억합니다.
close #363

[FE] Chore/#363 main hotfixes 커밋 반영

---

frontend/src/components/Layout/index.tsx

아이크 머지 후 충돌 해결
반응형 브랜치와 지도 타입 매긴거 머지

[FE] Fix/ 머지 후 충돌 해결

---

backend/src/main/java/com/mapbefine/mapbefine/auth/infrastructure/JwtTokenProvider.java
backend/src/main/java/com/mapbefine/mapbefine/auth/presentation/LoginController.java
backend/src/main/java/com/mapbefine/mapbefine/common/config/WebConfig.java

[BE] Fix/#426 Token CORS 재설정

---

backend/src/main/java/com/mapbefine/mapbefine/auth/application/TokenService.java
backend/src/main/java/com/mapbefine/mapbefine/auth/domain/token/RefreshTokenRepository.java
backend/src/main/java/com/mapbefine/mapbefine/auth/infrastructure/JwtTokenProvider.java
backend/src/main/java/com/mapbefine/mapbefine/auth/presentation/LoginController.java
backend/src/main/java/com/mapbefine/mapbefine/common/config/WebConfig.java

[BE] HotFix/#426 Refresh Token 중복 저장 방지 로직 수정

---

backend/src/main/java/com/mapbefine/mapbefine/common/entity/BaseTimeEntity.java
backend/src/main/java/com/mapbefine/mapbefine/pin/domain/Pin.java
backend/src/main/java/com/mapbefine/mapbefine/pin/domain/PinRepository.java
backend/src/main/java/com/mapbefine/mapbefine/topic/application/TopicQueryService.java
backend/src/main/java/com/mapbefine/mapbefine/topic/domain/Topic.java
backend/src/main/java/com/mapbefine/mapbefine/topic/domain/TopicRepository.java
backend/src/main/java/com/mapbefine/mapbefine/topic/dto/response/TopicDetailResponse.java
backend/src/main/java/com/mapbefine/mapbefine/topic/dto/response/TopicResponse.java
backend/src/main/resources/data-default.sql
backend/src/test/java/com/mapbefine/mapbefine/common/annotation/ServiceTest.java
backend/src/test/java/com/mapbefine/mapbefine/pin/application/PinCommandServiceTest.java
backend/src/test/java/com/mapbefine/mapbefine/topic/TopicIntegrationTest.java
backend/src/test/java/com/mapbefine/mapbefine/topic/application/TopicQueryServiceTest.java
backend/src/test/java/com/mapbefine/mapbefine/topic/domain/TopicTest.java

- Topic, Pin : `@PrePersist`, `@PreUpdate` EntityListener 메서드 추가
- TopicQueryService : 최신순 토픽 조회 시, 기존 Pin을 모두 가져와 가공 후 정렬해야 했던 것을 lastPinUpdatedAt 컬럼으로 바로 정렬 가능하도록 바뀌었습니다.
- TopicRepository(정렬 조회 쿼리 추가), PinRepository(정렬 조회 쿼리 삭제)
- TopicResponse, TopicDetailResponse : updatedAt 필드에 topic.getLastUpdatedAt을 넣어줍니다.
- 관련 테스트 작성
#400 참조.
> 논의할 땐 핀이 '추가'되는 일시만 기준으로 얘기했었는데, 기존 '새로울 지도' 구현 코드를 보니 핀이 변경된 일시도 고려하고 있었더라구요. 핀이 변경된 일시도 '업데이트 일자'에 반영하는 게 자연스러운 것 같아 똑같이 진행했습니다!
토픽을 조회할 때, 토픽이 가진 핀이 추가/변경된 일시를 '업데이트 일자'로 보여주는데,  
항상 핀을 가져와 이를 조회하는 대신 ,  
토픽에 `lastPinUpdatedAt` 컬럼을 두고 핀이 추가/변경될 때 해당 컬럼을 업데이트하도록 합니다.
쓰기 작업보다 조회 작업이 더 많을 것으로 예상되어, 이 방식이 더 성능적으로 유리하다고 판단했습니다.
기존에 저희가 `createdAt`, `updatedAt`을 저장할 때에는, `AuditingEntityListner.class`에 의해 **객체를 영속화 할 때** 해당 값이 저장됩니다.
(때문에 영속화 하기 전에 객체에 …

[BE] Refactor/#400 토픽 조회 시 업데이트 일시를 최근에 핀이 추가/변경된 일시로 변경

---

backend/src/main/java/com/mapbefine/mapbefine/auth/exception/AuthErrorCode.java
backend/src/main/java/com/mapbefine/mapbefine/auth/infrastructure/JwtTokenProvider.java
backend/src/main/java/com/mapbefine/mapbefine/auth/presentation/LoginController.java
backend/src/main/java/com/mapbefine/mapbefine/common/config/WebConfig.java

[BE] HOTFix/#424 validateTokensForReissue 디버깅을 위한 에러코드 추가

---

frontend/src/apis/getApi.ts

hotfix: 재발급시 getItem 부분 수정

---

frontend/src/apis/getApi.ts

fix: Promise 상태로 분기처리하여 재요청 차단

---

frontend/cypress.config.ts
frontend/cypress/e2e/mapbefine.cy.ts
frontend/src/components/AuthorityRadioContainer/index.tsx
frontend/src/components/TopicInfo/UpdatedTopicInfo.tsx
frontend/src/pages/NewTopic.tsx
frontend/src/pages/SelectedTopic.tsx
frontend/src/types/Topic.ts

토픽 수정에 대하여 다음과 오류를 수정한다.
* 모아보기 상태에서 토픽 수정을 하지 못한 오류
* 토픽 수정 시 토픽을 생성할 때 설정한 권한을 불러와 UI를 업데이트 하지 못하던 오류
* '기존에 선택한 인원' 들을 조건적으로 표시하지 못하던 오류 수정
이미지를 추가할 수 없어 토픽 추가 및 수정이 안 되는 상황이기에, 실제 API 통신은 GET 만 진행하였습니다. 예기치 못한 오류가 있을 수도 있습니다.

[FE] Fix/permission 토픽 권한 수정 오류 해결

---

frontend/src/hooks/useCompressImage.ts
frontend/src/pages/NewPin.tsx
frontend/src/pages/NewTopic.tsx
frontend/src/pages/PinDetail.tsx

이미지 압축 기능 구현
close #435 
이미지 압축 라이브러리 browser-image-compression의 참고자료입니다!! 
https://www.abstractapi.com/guides/how-to-compress-an-image-in-react
10671912 : 10.7MB-> 97891 : 90KB
225370: 225KB -> 113697: 110KB
1822: 2KB -> 1061: 1KB

[FE] Feature/#435 이미지 압축 기능 구현

---

frontend/src/components/AuthorityRadioContainer/index.tsx
frontend/src/components/TopicInfo/UpdatedTopicInfo.tsx
frontend/src/pages/NewTopic.tsx

[FE] hotfix: 네이밍 변경 누락 오류 수정 및 네이밍 통일성 준수

---

frontend/src/components/Layout/Navbar.tsx
frontend/src/components/Layout/NavbarItem.tsx
frontend/src/hooks/useNavigator.ts
frontend/src/pages/Home.tsx

홈페이지 및 Navbar 중복로직 제거 및 컴포넌트 분리
- Navbar의 반복되는 로직을 제거한다
- Navbar의 각 항목( 홈, 즐겨찾기 등)을 NavbarItem 컴포넌트로 분리한다
- 페이지 이동 로직 및 keyDown 이벤트를 분리한다
-  기존에 있던 useNavigator에 각 컴포넌트에 흩어져있던 페이지 이동 로직을 모아뒀습니다. 
홈과 Navbar이외에 컴포넌트에는 아직 변경된 사항을 적용 안했습니다
#404 
closed #404

[ FE ] Refactor/#404 홈페이지 및 Navbar 리팩토링

---

frontend/babel.config.js
frontend/src/router.tsx

동적 임포트와 tree shaking으로 코드 스플리팅
close #469

[FE] Refactor/#469 동적 임포트와 tree shaking으로 코드 스플리팅

---

frontend/package-lock.json
frontend/package.json
frontend/src/router.tsx

Google Analytics 적용
close #495

[FE] Feature/#495 Google Analytics 적용

---

backend/src/main/java/com/mapbefine/mapbefine/atlas/domain/AtlasRepository.java
backend/src/main/java/com/mapbefine/mapbefine/bookmark/application/BookmarkCommandService.java
backend/src/main/java/com/mapbefine/mapbefine/bookmark/domain/BookmarkRepository.java
backend/src/main/java/com/mapbefine/mapbefine/location/domain/Location.java
backend/src/main/java/com/mapbefine/mapbefine/member/application/MemberQueryService.java
backend/src/main/java/com/mapbefine/mapbefine/pin/domain/Pin.java
backend/src/main/java/com/mapbefine/mapbefine/pin/domain/PinRepository.java
backend/src/main/java/com/mapbefine/mapbefine/topic/application/TopicQueryService.java
backend/src/main/java/com/mapbefine/mapbefine/topic/domain/Topic.java
backend/src/main/java/com/mapbefine/mapbefine/topic/domain/TopicRepository.java
backend/src/test/java/com/mapbefine/mapbefine/admin/AdminIntegrationTest.java
backend/src/test/java/com/mapbefine/mapbefine/auth/application/TokenServiceTest.java
backend/src/test/java/com/mapbefine/mapbefine/bookmark/application/BookmarkCommandServiceTest.java
backend/src/test/java/com/mapbefine/mapbefine/permission/domain/PermissionTest.java
backend/src/test/java/com/mapbefine/mapbefine/pin/domain/PinTest.java
backend/src/test/java/com/mapbefine/mapbefine/topic/TopicIntegrationTest.java
backend/src/test/java/com/mapbefine/mapbefine/topic/application/TopicCommandServiceTest.java

성능 개선을 위해 조회 쿼리를 개선하였습니다. (항상 필요한 정보를 지연 로딩 대신 즉시 로딩 + fetch 조인 적용)
`@EntityGraph`를 이용해 fetch join으로 조회하도록 합니다.
3인 페어로 진행하여, 준팍 확인하시면 머지 진행하도록 하겠습니다!
(노션의 BE 공간 - 쿼리 개선 기록 참조)
closed #494

[BE] Refactor/#494 성능 개선을 위한 조회 쿼리 수정

---

frontend/src/components/Layout/index.tsx
frontend/src/pages/NewPin.tsx
frontend/src/pages/NewTopic.tsx
frontend/src/pages/SeeTogetherTopics.tsx

* 지도생성 및 핀 생성 페이지에서 지도 상하가 반전되어 나오는 정책을 변경한다. (지도: 상 , 사이드바: 하 로 모든 페이지를 고정한다.)
* 핀 생성 페이지 접속 시 장소 이름으로 오토 포커스 되는 기능을 제거한다.
* 지도 단일 조회 이후 지도 생성, 핀생성 페이지 이동 시 기존에 조회한 핀이 잔류하던 문제를 해결한다.
close #513

[FE] Refactor/#513 지도 생성 및 핀 생성 페이지 지도 위치 조정

---

frontend/src/components/MyInfo/UpdateMyInfo.tsx
frontend/src/components/MyInfo/index.tsx
frontend/src/constants/index.ts
frontend/src/pages/Home.tsx
frontend/src/types/Profile.ts

마이페이지 닉네임 변경 시 이미지 사라지던 오류 수정합니다.

[FE] Fix/myinfo 마이페이지 닉네임 변경 시 이미지 사라지던 오류 수정

---

backend/src/main/java/com/mapbefine/mapbefine/pin/domain/Pin.java
backend/src/main/java/com/mapbefine/mapbefine/topic/domain/Topic.java
backend/src/main/java/com/mapbefine/mapbefine/topic/domain/TopicRepository.java
backend/src/test/java/com/mapbefine/mapbefine/permission/domain/PermissionTest.java
backend/src/test/java/com/mapbefine/mapbefine/pin/domain/PinTest.java
backend/src/test/java/com/mapbefine/mapbefine/topic/application/TopicCommandServiceTest.java

Topic
Topic 클래스의 자료구조를 List로 변경하였습니다.
기존에 multiple Bag(?) 오류로 인해, Set을 사용하였는데 이 경우, 데이터베이스에서 데이터를 읽어올 때, 순서를 보장하지 않게 됩니다.
어플리케이션 단에서 순서가 보장되지 않아서 문제가 발생하는 것이 아니라, 데이터베이스에서 읽어올 때 발생하는 문제입니다.
이에 따라, 기존 매튜의 hotfix로 문제가 해결되지 않았던 것입니다.
성능 개선 과정에서, Bookmark count를 컬럼으로 추가함에 따라 기존 `@EntityGraph` 사용시 함께 fetch join 해오던 Bookmarks를 제거하였습니다.
이로 인해, mutliple bag 관련 예외가 발생하지 않으며, 데이터의 기존 순서 또한 보장될 수 있습니다.
**참고 사항**
별개로, 현재 프론트엔드에서 토픽을 상세조회할 때 2번의 API 요청이 발생하고 있습니다.
또한, 토픽 내의 핀의 정보를 클릭할 때마다, 토픽 상세 조회 API를 호출하고 있습니다.
이 부분은 세인 및 아이크에게 전달된 사항입니다.

Hotfix: 토픽 조회시 순서 보장하도록 수정 

---

frontend/src/components/TopicInfo/UpdatedTopicInfo.tsx
frontend/src/components/TopicInfo/index.tsx
frontend/src/context/MarkerContext.tsx
frontend/src/hooks/useAnimateClickedPin.ts
frontend/src/pages/Home.tsx
frontend/src/pages/SelectedTopic.tsx
frontend/webpack.common.js

* 단일, 다중 토픽 조회 시 GET 요청을 두 번 보내던 오류를 수정한다.
* 핀, 핀프리뷰 클릭하여 핀 상세 정보 요청시 토픽 조회 GET 요청을 지속해서 보내는 오류를 수정한다.
* 핀, 핀프리뷰 클릭 시 지도 줌인이 되지 않는 오류를 수정한다.
* 핀 infoWindow 디자인을 변경한다.
API env 테스트 console 있습니다.
close #522

[FE] Fix/#522 토픽 조회 중복 요청 오류, 핀 조회 시 토픽 조회 요청 오류 및 지도 줌인 오류 수정

---

backend/src/main/java/com/mapbefine/mapbefine/admin/application/AdminCommandService.java
backend/src/main/java/com/mapbefine/mapbefine/atlas/application/AtlasCommandService.java
backend/src/main/java/com/mapbefine/mapbefine/bookmark/application/BookmarkCommandService.java
backend/src/main/java/com/mapbefine/mapbefine/member/application/MemberQueryService.java
backend/src/main/java/com/mapbefine/mapbefine/permission/application/PermissionCommandService.java
backend/src/main/java/com/mapbefine/mapbefine/permission/application/PermissionQueryService.java
backend/src/main/java/com/mapbefine/mapbefine/pin/application/PinCommandService.java
backend/src/main/java/com/mapbefine/mapbefine/pin/application/PinQueryService.java
backend/src/main/java/com/mapbefine/mapbefine/pin/domain/PinImageRepository.java
backend/src/main/java/com/mapbefine/mapbefine/pin/domain/PinRepository.java
backend/src/main/java/com/mapbefine/mapbefine/topic/application/TopicCommandService.java
backend/src/main/java/com/mapbefine/mapbefine/topic/application/TopicQueryService.java
backend/src/main/java/com/mapbefine/mapbefine/topic/domain/TopicRepository.java
backend/src/test/java/com/mapbefine/mapbefine/admin/application/AdminCommandServiceTest.java
backend/src/test/java/com/mapbefine/mapbefine/pin/application/PinCommandServiceTest.java
backend/src/test/java/com/mapbefine/mapbefine/pin/application/PinQueryServiceTest.java
backend/src/test/java/com/mapbefine/mapbefine/pin/domain/PinImageRepositoryTest.java
backend/src/test/java/com/mapbefine/mapbefine/topic/application/TopicCommandServiceTest.java
backend/src/test/java/com/mapbefine/mapbefine/topic/application/TopicQueryServiceTest.java
backend/src/test/java/com/mapbefine/mapbefine/topic/domain/TopicRepositoryTest.java

- Topic, Pin, PinImage (Soft delete 대상 도메인)
- 엔티티에 일괄 적용하여 통일성을 부여하는 대신, 테스트 코드의 적은 변경사항을 위해 Repository 메서드를 수정하였습니다.
- 조회 시 isDeletedFalse 인 레코드만 가져오도록 Repository 메서드를 수정합니다.
- 테스트에서 사용하는 조회 메서드는 그대로 유지합니다. (테스트에서도 isDeletedFalse로 가져오는 게 로직 상 더 나은 일부 경우,  수정하였음)
- XXXQueryServiceTest에 해당 내용 테스트를 추가했습니다. Topic 다건 조회의 경우 비슷한 로직의 테스트가 많아 모아보기, 전체조회 하는 메서드에 대해서만 우선 테스트 작성했습니다.
운영 서버에 빠른 반영이 필요한 사안이라 main 의 hotfix로 올립니다.  
이 PR 이후 develop-BE-2 브랜치는 main pull 땡겨오고 작업하면 좋을 것 같아요
추가로 mutlipleBag 발생 문제로 인해 Topic의 findByIdAndIsDeletedFalse 조인 항목 중 bookmarks를 삭제했습니다.
closed #473

[BE] Hotfix/#473 Soft Delete 반영해 조회하도록 쿼리 수정

---

frontend/src/components/PinsOfTopic/index.tsx
frontend/src/components/TopicInfo/index.tsx
frontend/src/pages/SelectedTopic.tsx

* 모아보기 상태에서 핀 조회 시 에러가 발생하는 오류를 해결한다.
main 브랜치 머지 일정 때문에 오늘 오전까지만 확인받겠습니다. (이후는 hotfix 처럼 머지할께요.)
close #524

[FE] fix/#524 모아보기 상태에서 핀 조회가 안되는 오류 수정

---

frontend/src/components/Layout/index.tsx

* 반응형 사이즈에서 지도 조회 페이지
* 반응형 사이즈에서 로고 영역 배경을 투명하게 하여 지도를 보다 더 넓게 볼 수 있도록 합니다.

[FE] design: 반응형 사이즈에서 로고 영역 배경 투명하게 적용

---

backend/src/main/java/com/mapbefine/mapbefine/auth/domain/AuthMember.java
backend/src/main/java/com/mapbefine/mapbefine/auth/domain/member/Admin.java
backend/src/main/java/com/mapbefine/mapbefine/auth/domain/member/Guest.java
backend/src/main/java/com/mapbefine/mapbefine/auth/domain/member/User.java
backend/src/main/java/com/mapbefine/mapbefine/common/interceptor/AuthInterceptor.java
backend/src/main/java/com/mapbefine/mapbefine/member/application/MemberQueryService.java
backend/src/main/java/com/mapbefine/mapbefine/member/dto/response/MemberResponse.java
backend/src/main/java/com/mapbefine/mapbefine/member/exception/MemberErrorCode.java
backend/src/main/java/com/mapbefine/mapbefine/member/presentation/MemberController.java
backend/src/main/resources/data-default.sql
backend/src/test/java/com/mapbefine/mapbefine/member/application/MemberQueryServiceTest.java
backend/src/test/java/com/mapbefine/mapbefine/member/domain/MemberResponseTest.java
backend/src/test/java/com/mapbefine/mapbefine/member/presentation/MemberControllerTest.java
backend/src/test/java/com/mapbefine/mapbefine/permission/presentation/PermissionControllerTest.java

- #537
- #538
에 대한 이슈 해결 PR입니다.
- #537, #538 해결
- Interceptor, ArgumentResolver 관련 리팩터링 추후 진행 예정
- 회원 상세 조회 시 자기 자신만 조회 가능하도록 수정
- API 명세 추후 변경 예정
- **추가로 (관리자 API가 아닌) 회원 조회 시 stream.filter로 Member.isNormalStatus 인 경우만 조회하도록 했습니다.**
- 쿼리 where절에 거는 방법도 있을텐데 이 부분은 머지 후 추가로 의견 나눠보면 좋을 것 같습니다!
closed #537 #538

[BE] Hotfix/#537,#538 회원 정보 관련 이슈 해결

---

backend/src/docs/asciidoc/member.adoc
backend/src/main/java/com/mapbefine/mapbefine/member/application/MemberQueryService.java
backend/src/main/java/com/mapbefine/mapbefine/member/presentation/MemberController.java
backend/src/test/java/com/mapbefine/mapbefine/member/MemberIntegrationTest.java
backend/src/test/java/com/mapbefine/mapbefine/member/application/MemberQueryServiceTest.java
backend/src/test/java/com/mapbefine/mapbefine/member/presentation/MemberControllerTest.java

#547 참조
#547 참조
- MemberController
- MemberQueryService findById -> findProfile
- 관련 테스트
- RestDocs
~~API 명세의 변경으로, 프론트 측 해당 코드 변경 PR과 시점을 맞추어 배포할 필요가 있습니다.~~   (현재 해당 API 사용하지 않음)
closed #547

[BE] Refactor/#547 로그인 회원 프로필 조회 API 명세 변경

---

.github/workflows/fe-merge-dev.yml
frontend/src/apis/getPoiApi.ts
frontend/src/components/common/Input/Autocomplete.tsx
frontend/src/hooks/useClickedCoordinate.ts
frontend/src/pages/NewPin.tsx
frontend/src/types/Poi.ts
frontend/src/types/tmap.d.ts

- 핀을 추가하는 경우 식당명과 같은 키워드로도 위치 검색 가능하도록 구현
- tmap poi 적용으로 장소명으로도 주소 검색(자동완성) 가능
- 연관 검색어 요청 debounce 적용
- tmap zoom level관련 수정
- tmap api를 일단 ga처럼 숨기긴 해뒀는데 잘 될지 모르겠네여...
- new-pin 페이지의 이전 input 코드를 주석 처리만 해둬서 확인해보고 전부 삭제해도 되면 반영 예정입니다
- 실행 안될경우 대비해 스크린샷 첨부합니다
#564 
closed #564

feat/#564 poi 적용

---

.github/workflows/be-merge-dev.yml
.github/workflows/be-merge-prod.yml
backend/Dockerfile-dev
backend/Dockerfile-prod
backend/src/main/resources/logback-spring.xml

#545 참조
블루 그린 무중단 배포 구현을 위한 작성파일입니다. (운영서버는 개발서버 작동 확인 후 반영 예정)  
EC2 내에 컨테이너 두 개를 띄우는 방식으로 구현했습니다.
closed #545
배포 방식(블루-그린) 참고: https://jay-ji.tistory.com/99
설정 파일 참고: [https://velog.io/@hooni_/Blue-Green-무중단-배포](https://velog.io/@hooni_/Blue-Green-%EB%AC%B4%EC%A4%91%EB%8B%A8-%EB%B0%B0%ED%8F%AC)

[BE] Env/#545 무중단 배포를 위한 구성 파일 작성

---

backend/src/docs/asciidoc/admin.adoc
backend/src/docs/asciidoc/pin.adoc
backend/src/docs/asciidoc/topic.adoc
backend/src/main/java/com/mapbefine/mapbefine/member/application/MemberQueryService.java
backend/src/main/java/com/mapbefine/mapbefine/pin/presentation/PinController.java
backend/src/main/java/com/mapbefine/mapbefine/topic/presentation/TopicController.java
backend/src/test/java/com/mapbefine/mapbefine/admin/presentation/AdminControllerTest.java
backend/src/test/java/com/mapbefine/mapbefine/atlas/presentation/AtlasControllerTest.java
backend/src/test/java/com/mapbefine/mapbefine/auth/presentation/LoginControllerTest.java
backend/src/test/java/com/mapbefine/mapbefine/bookmark/presentation/BookmarkControllerTest.java
backend/src/test/java/com/mapbefine/mapbefine/location/presentation/LocationControllerTest.java
backend/src/test/java/com/mapbefine/mapbefine/member/presentation/MemberControllerTest.java
backend/src/test/java/com/mapbefine/mapbefine/permission/presentation/PermissionControllerTest.java
backend/src/test/java/com/mapbefine/mapbefine/pin/presentation/PinControllerTest.java
backend/src/test/java/com/mapbefine/mapbefine/topic/presentation/TopicControllerTest.java

모든 RestDocs 테스트 코드
- 모든 테스트 코드에 상태 코드 검증 조건을 추가했습니다. (`.andExpect()`) 기존에 이 조건이 없었어서 상태코드가 500이어도 테스트가 통과하는 문제가 있었습니다. **RestDocs 테스트 추가 작성 시 참고 부탁드립니다.**
- 이 과정에서 명세서에는 올려놓지 않았더라도 실패가 확인된 테스트들을 모두 수정했습니다.
- 이제 이미지 명세도 RestDocs 명세서에서 확인 가능합니다.
- LoginControllerTest의 실패 원인은 MockMvcTest 상의 쿠키 설정이었습니다. (해당 커밋 바디 참조)
- ControllerTest에서 관리자 인증 방식 내용을 반영하여, 관리자 API 명세서를 다시 활성화했습니다.
- 내부 로직이 불완전해 사용되면 안되는 API들을 adoc만 삭제했습니다. (Topic 삭제, Pin 삭제)
closed #563

[BE] Refactor/#563 RestDocs 응답 오류(500) 해결 및 상태코드 검증 추가

---

frontend/src/apis/putApi.ts
frontend/src/assets/remove_image_icon.svg
frontend/src/components/PinImageContainer/index.tsx
frontend/src/components/TopicInfo/UpdatedTopicInfo.tsx
frontend/src/pages/PinDetail.tsx

- 토픽 이미지 수정 및 핀 이미지 삭제 기능
close #550

[FE] Feature/#550 토픽 이미지 수정 및 핀 이미지 삭제 기능

---

frontend/src/components/Map/index.tsx
frontend/src/hooks/useGeolocation.ts

Hotfix/refactor: 현재 위치 요청 로직 변경

---

frontend/src/components/common/Input/Autocomplete.tsx
frontend/src/components/common/Input/ReplyComment.tsx
frontend/src/components/common/Input/SingleComment.tsx
frontend/src/constants/index.ts
frontend/src/pages/PinDetail.tsx
frontend/src/pages/UpdatedPinDetail.tsx
frontend/src/types/Comment.ts

- 댓글 및 대댓글 기능을 구현한다.
- 수정,삭제 기능을 구현한다.
- pinDetail페이지에서 댓글 추가, 수정, 삭제 기능 구현했습니다
- UI관련 개선사항은 BE 머지 되고 빠르게 할 예정입니다 
#597 
closed #597

[FE] Feat/#597 댓글 기능 구현

---

frontend/src/components/PinImageContainer/index.tsx
frontend/src/components/TopicInfo/UpdatedTopicInfo.tsx
frontend/src/pages/NewTopic.tsx
frontend/src/pages/PinDetail.tsx

image swiper 적용 및 image size limit 적용
close #604

[FE] Feat/#604 image swiper 적용 및 image size limit 적용

---

frontend/src/components/Layout/index.tsx
frontend/src/components/PullPin/index.tsx
frontend/src/hooks/useFocusToMarkers.ts

* 지도 조회 시 바운더리 경계에 맞게 지도가 자동으로 줌인 되지 않던 오류 수정

[FE] Hotfix/map panto 오류 수정

---

frontend/.eslintrc.js
frontend/src/components/Map/index.tsx
frontend/src/components/common/Flex/index.ts
frontend/src/constants/index.ts
frontend/src/constants/pinImage.ts
frontend/src/context/MarkerContext.tsx
frontend/src/hooks/useAnimateClickedPin.ts
frontend/src/hooks/useClickedCoordinate.ts
frontend/src/hooks/useFocusToMarkers.ts
frontend/src/hooks/useMapClick.ts
frontend/src/hooks/useUpdateCoordinates.ts
frontend/src/pages/SelectedTopic.tsx
frontend/src/store/mapInstance.ts
frontend/src/types/tmap.d.ts

* Flex 공통 컴포넌트 interface 작업 (본문과는 관련없지만 에러 띄워진 상태가 지속되기에 리팩토링하였습니다.)
* 토픽 단일 조회 지도 클러스터링 (모아보기는 추후 진행)
드디어 클러스터링을 완료했습니다. (단, 토픽 단일 조회페이지에만 적용했습니다.)
주 원리는 다음과 같습니다.
위와 같이 현재 지도 사이즈의 실제 우상단 끝점 좌표, 좌하단 끝점 좌표를 얻어냅니다. Map API 중의 getBounds 라는 함수를 쓰면 얻어낼 수 있습니다. 우상단, 좌하단 끝점 좌표를 알면 모든 꼭짓점의 좌표를 알아낼 수 있겠죠?
알아낸 좌표를 가지고 지도 스크린 사이즈 만큼의 '실제 거리'를 알 수 있습니다. 이는 LatLng API 중에 distanceTo 라는 함수를 쓰면 두 좌표간의 거리 차이를 구할 수 있는데, 이를 사용해서 구할 수 있습니다.
그런 다음 이제 스크린 사이즈 즉, 지도의 width 값을 알아내야합니다. 이는 Map API 중에 realToScreen 함수를 사용하여 알아낼 수 있습니다. 실제 좌표를 스크린 좌표로 변환해줍니다. 이전에 지도 모서리의 모든 실제 좌표값을 알 수 있었으니, 스크린 사이즈의 좌표값도 쉽게 알아낼 수 있겠죠? 그 좌표값의 x 축 값 차이가 지도의 width가 됩니다.
이제 마지막으로 지도 위의 **핀이 차지하는 실제 거리**를 알아야하는데요, 핀이 차지하는 지도상 실제 거리는 지도의 줌 상태에 따라서 달라집니다. 줌을 최대로 확대하면 핀이 차지하는 실제 거리는 몇 m에 불과할 것이고, 최대로 축소하면 수십 km 가 될 수도 있겠죠. 이 정보를 백엔드에 넘겨주면 …

[FE] Refactor/#613 지도 클러스터링 기능 추가 및 지도 상태 리팩토링

---

backend/src/main/java/com/mapbefine/mapbefine/admin/application/AdminCommandService.java
backend/src/test/java/com/mapbefine/mapbefine/admin/AdminIntegrationTest.java
backend/src/test/java/com/mapbefine/mapbefine/admin/application/AdminCommandServiceTest.java

- AdminCommandService
- 관련 테스트 코드
#619 참조 부탁드립니다. 
간단히 말하면 `pin.decreaseTopicPinCount()`에 대한 변경 감지가 발생하지 않는 문제입니다.
```java
public void deletePin(Long pinId) {
Pin pin = pinRepository.findById(pinId)
.orElseThrow(() -> new PinNotFoundException(PIN_NOT_FOUND, pinId));
pin.decreaseTopicPinCount();
pinRepository.flush(); // 추가 된 코드
pinImageRepository.deleteAllByPinId(pinId);
pinRepository.deleteById(pin.getId());
}
```
위 코드에서, deleteXXX 메서드들에 의해 `clearAutomatically = true`로 설정된 네이티브 쿼리가 발생합니다.
이 때 영속성 컨텍스트가 데이터베이스의 내용과 동일하게 초기화됩니다.
따라서 윗줄에서 pin.decreaseTopicPinCount()를 해주었어도,  
커밋하는 시점에서는 영속성 컨텍스트에 해당 변경사항이 반영되지 않는 것입니다.  
그래서 해당 변경을 반영할 수 있도록 flush를 추가했습니다.
**실제 운영 환경에 바로 노출되는 부분이므로 main에 대한 hotfix 먼저 올립니다.**
**해당 브랜치 머지 후, dev 브랜치 작업하면 main pull 받은 후 작업부탁드려용**
- 비슷하게, 역정규화된 컬럼의 정보에 대해서 …

[BE] Hotfix/#619 핀 삭제 시 토픽의 핀 개수가 업데이트되지 않는 버그 해결

---

frontend/src/components/PinPreview/index.tsx
frontend/src/components/PullPin/index.tsx
frontend/src/components/TopicCard/index.tsx
frontend/src/components/TopicInfo/index.tsx
frontend/src/constants/pinImage.ts
frontend/src/context/MarkerContext.tsx
frontend/src/hooks/useClickedCoordinate.ts
frontend/src/hooks/useRealDistanceOfPin.ts
frontend/src/pages/NewPin.tsx
frontend/src/pages/PinDetail.tsx
frontend/src/pages/SeeTogether.tsx
frontend/src/pages/SelectedTopic.tsx
frontend/src/types/tmap.d.ts

* 모아보기 페이지에 클러스터링 및 스크린 사이즈 마커 렌더링을 진행한다.
* SeeTogether 페이지에서 모아보기 핀인지 구분하고 정렬하는 과정의 로직이 조금 복잡합니다. 추후 모아보기 된의 색깔을 무지개 색에서 모아보기 된 핀들의 색깔로만 동적으로 만들어낼 계획이기에 이 리팩토링을 진행하면서 수정해보겠습니다.
close #620

[FE] Refactor/#620 모아보기 클러스터링

---

frontend/src/pages/SeeTogether.tsx
frontend/src/pages/SelectedTopic.tsx
frontend/src/types/tmap.d.ts

지도 회전 및 기울기 이벤트를 허용하나, 이후 지도를 움직이거나 줌인, 줌아웃하면 원래의 방향 bearing: 0, pitch: 0으로 돌려놓는다.
이는 모바일에서 줌인 줌아웃시 지도가 돌아가서 원래대로 돌려놓는데 불편함이 있었으며 클러스터링 안정화를 위해 위와 같이 작업한다.

[FE] Refactor 지도 회전 및 기울기 이벤트 시 지도를 원래대로 조정

---

frontend/.eslintrc.js
frontend/src/components/Map/index.tsx
frontend/src/components/PinPreview/index.tsx
frontend/src/components/PullPin/index.tsx
frontend/src/components/TopicCard/index.tsx
frontend/src/components/TopicInfo/index.tsx
frontend/src/components/common/Flex/index.ts
frontend/src/constants/index.ts
frontend/src/constants/pinImage.ts
frontend/src/context/MarkerContext.tsx
frontend/src/hooks/useAnimateClickedPin.ts
frontend/src/hooks/useClickedCoordinate.ts
frontend/src/hooks/useFocusToMarkers.ts
frontend/src/hooks/useMapClick.ts
frontend/src/hooks/useRealDistanceOfPin.ts
frontend/src/hooks/useUpdateCoordinates.ts
frontend/src/pages/NewPin.tsx
frontend/src/pages/PinDetail.tsx
frontend/src/pages/SeeTogether.tsx
frontend/src/pages/SelectedTopic.tsx
frontend/src/store/mapInstance.ts
frontend/src/types/tmap.d.ts

* 지도 컴포넌트와 그에 관련된 커스텀 훅
* 모아보기, 단일 토픽 조회 페이지
* 지도 클러스터링 및 스크린 사이즈 렌더링 적용으로 렌더링 최적화 관련 기능을 도입한다.
* 지도 줌, 드래그 이벤트 핸들링을 추가한다.
* 지도 회전, 기울이기를 한 시점에서 허용한다. 이후 줌, 드래그 이벤트가 발생하면 최초의 모습으로 자동 조정한다. (pitch(기울기):0, bearing(회전): 0)

[FE] 2.1.0 배포

---

frontend/src/apis/Patrick/http.ts
frontend/src/apis/Patrick/index.ts
frontend/src/components/TopicCardList/index.tsx
frontend/src/hooks/queries/useProfileList.ts
frontend/src/index.tsx
frontend/src/router.tsx

- Profile 페이지 API 로직 수정 및 React-Query 적용
- http 모듈 추가
- Profile get api 추가
- Tanstack query 도입을 위한 hook 추가
- 리팩토링 필요한 부분 수정
#643

[FE] Refactor/#643: Profile 페이지 API 로직 수정 및 React-Query 적용

---

frontend/src/api/http.ts
frontend/src/api/index.ts
frontend/src/components/TopicCard/index.tsx
frontend/src/components/TopicCardContainer/index.tsx
frontend/src/hooks/api/useTopicsQuery.ts
frontend/src/index.tsx

- Home페이지 tanstack-query 및 axios 적용
- 새로운 api 폴더를 생성해서 http.ts와 index.ts 파일을 만들었습니다
- http.ts는 http메소드, index.ts는 지도들을 가져오는 getTopics함수가 있습니다
- 홈 화면에서 각각 데이터를 fetch하는 곳은 TopicListContainer의 TopicCardContainer라서 useState와 useEffect를 useQuery로 대체했습니다
- 이전에 자식 컴포넌트에 getTopicsFromServer로 넘겨주던 함수를 refetch로 대체했는데 문제 없는지???
- 인기 급상승 지도의 지도1을 모아보기 해제하면 새로울지도의 지도1에 반영 안되는 문제
- getTopicsFromServer의 정확한 목적 헷갈리네여
- refetch로 대체가능하면 error랑 로딩 처리 어떻게 할지 정해보죠
#645 
#645 
https://github.com/ssi02014/react-query-tutorial

[FE] Refactor/#645: Home 페이지 API 로직 수정 및 React-Query 적용
