woowacourse-teams/2023-map-befine

frontend/.eslintrc.js
#️⃣연관된 이슈
https://github.com/woowacourse-teams/2023-map-befine/issues/25
📝작업 내용
eslint에서 모듈 시스템 및 parser 에러 해결을 위해 코드를 추가한다.
close https://github.com/woowacourse-teams/2023-map-befine/issues/25
=> [FE]Chore/#25 eslint settings error 해결

frontend/src/GlobalStyle.ts, frontend/src/index.tsx, frontend/src/themes/color.ts, frontend/src/themes/fontSize.ts, frontend/src/themes/index.ts, frontend/src/themes/radius.ts, frontend/src/themes/spacing.ts
#️⃣연관된 이슈
https://github.com/woowacourse-teams/2023-map-befine/issues/12
📝작업 내용
ThemeProvider와 GlobalStyle로 공통 스타일 속성을 지정한다.
close https://github.com/woowacourse-teams/2023-map-befine/issues/12
=> [FE]Design/#12 ThemeProvider와 GlobalStyle 공통 스타일 속성 지정

frontend/src/App.tsx, frontend/src/components/common/Box/index.ts, frontend/src/components/common/Button/index.ts, frontend/src/components/common/Flex/index.ts, frontend/src/components/common/Input/index.ts, frontend/src/components/common/Layout/index.tsx, frontend/src/components/common/Text/index.ts, frontend/src/pages/Home.tsx, frontend/src/pages/NewPin.tsx, frontend/src/pages/NewTopic.tsx, frontend/src/pages/PinDetail.tsx, frontend/src/pages/Topics.tsx, frontend/src/themes/fontWeight.ts, frontend/src/themes/index.ts
#️⃣연관된 이슈
https://github.com/woowacourse-teams/2023-map-befine/issues/16
📝작업 내용
공통 컴포넌트를 구현한다. 
close https://github.com/woowacourse-teams/2023-map-befine/issues/16
=> [FE]Feat/#16 공통 컴포넌트 구현

frontend/src/components/common/Space/index.ts
#️⃣연관된 이슈
https://github.com/woowacourse-teams/2023-map-befine/issues/33
📝작업 내용
스페이싱 공통 컴포넌트를 구현한다. 
close https://github.com/woowacourse-teams/2023-map-befine/issues/33
=> [FE]Feat/#33 스페이싱 공통 컴포넌트 구현

frontend/package-lock.json, frontend/package.json, frontend/public/index.html, frontend/src/App.tsx, frontend/src/index.tsx
react-router-dom 라이브러리를 사용해 라우팅 설정
메인 페이지, 토픽 목록 페이지, 핀 상세보기 페이지 라우팅 설정
close #13
=> [FE]Feat/#13 React Router 기능 구현

frontend/public/mockServiceWorker.js, frontend/src/index.tsx, frontend/src/mocks/browser.js, frontend/src/mocks/handlers.js
MSW 환경 설정
프론트엔드의 요청에 가짜 데이터를 응답해주는 MSW 초기 설정을 한다.
close #49
=> [FE]Feat/#49 MSW 환경 설정

frontend/src/components/common/Box/index.ts, frontend/src/components/common/Layout/index.tsx, frontend/src/components/common/Text/index.ts
공통 컴포넌트 속성 변경
생각하지 못했던 속성들을 이미 만들어 두었던 공통 컴포넌트에 추가한다.
close #52
=> [FE]Refactor/#52 공통 컴포넌트 속성 변경

frontend/src/components/common/Input/index.ts, frontend/src/components/common/Textarea/index.ts, frontend/src/pages/NewPin.tsx, frontend/src/pages/NewTopic.tsx
=> [FE]Feat/#31 토픽 및 핀 생성 페이지 구현

frontend/package-lock.json, frontend/package.json, frontend/public/mockServiceWorker.js, frontend/src/index.tsx, frontend/src/mocks/handlers.js, frontend/src/pages/NewTopic.tsx, frontend/src/pages/PinDetail.tsx, frontend/src/pages/SelectedTopic.tsx, frontend/src/utils/putApi.ts
핀 디테일 수정하기 페이지 구현 
핀 상세정보 수정하는 기능 추가 및 msw 연동
closed #77
=> [FE]Feat/#77 핀 디테일 수정하기 페이지 구현 

backend/src/main/java/com/mapbefine/mapbefine/dto/PinCreateRequest.java, backend/src/main/java/com/mapbefine/mapbefine/entity/Coordinate.java, backend/src/main/java/com/mapbefine/mapbefine/service/PinCommandService.java, backend/src/test/java/com/mapbefine/mapbefine/service/PinCommandServiceTest.java
PinCreateRequest
Coordinate
- PinCreateRequest
위경도 값을 BigDecimal -> String 으로 변경
- Coordintae
정적 팩토리 메서드 추가
#92 
closed #92
=> [BE] 핀 생성 요청 DTO 수정

backend/src/test/java/com/mapbefine/mapbefine/controller/PinControllerTest.java
PinCreateRequest 변경에 따른 테스트 코드 수정
서로 다른 브랜치에서 작업한 뒤, Merge 과정에서 변경된 Request가 테스트 코드에 반영되지 않았던 것 같아요.
#91 
#93
=> [BE] PinCreateRequest 변경에 따른 테스트 코드 수정

frontend/src/GlobalStyle.ts, frontend/src/components/PinPreview/index.tsx, frontend/src/components/TopicCard/index.tsx, frontend/src/components/TopicInfo/index.tsx, frontend/src/pages/Home.tsx, frontend/src/pages/NewPin.tsx, frontend/src/pages/NewTopic.tsx, frontend/src/pages/PinDetail.tsx, frontend/src/pages/SelectedTopic.tsx
시맨틱 태그 적용
태그에 의미를 부여해 사이트 구조 파악을 용이하게 하기 위해 시맨틱 태그를 적용한다.
close #97
=> [FE]Feat/#97 시맨틱 태그 적용

frontend/.storybook/main.ts, frontend/.storybook/preview.tsx, frontend/.storybook/public/mockServiceWorker.js, frontend/package-lock.json, frontend/package.json, frontend/src/components/PinPreview/index.stories.ts, frontend/src/components/TopicCard/TopicCard.stories.ts, frontend/src/components/TopicInfo/index.stories.ts, frontend/src/pages/Home.stories.ts, frontend/src/pages/NewTopic.stories.ts, frontend/src/pages/PinDetail.stories.ts, frontend/webpack.dev.js
공통 컴포넌트를 제외한 TopicCard와 같은 컴포넌트, 페이지 단위의 컴포넌트들의 스토리북 코드
공통 컴포넌트를 제외한 컴포넌트, 페이지 단위의 컴포넌트의 스토리북 코드를 작성
.storybook main과 preview 설정을 위한 변경 있습니다.
closed #102
=> [FE]Test/#102  공통 컴포넌트 이외의 컴포넌트 스토리북 코드 작성 

.github/workflows/gradle.yml
깃허브 액션 설정
깃허브 액션을 통해 CI를 구축하였습니다.
빌드 및 테스트를 수행하며, 테스트 수행 결과를 코멘트로 남겨줍니다.
https://github.com/EnricoMi/publish-unit-test-result-action
=> [BE] 깃허브 액션 설정 (CI)

.github/workflows/gradle.yml
worksflows (gradle.yml)
기존 CI 코드 수정 및 CD 코드 추가했습니다.
4인 페어로 진행한 내용이기 때문에, 별도의 코멘트없이 merge 하겠습니다.
#119
closed #119
=> [BE] Github Action workflows CD 추가

backend/src/main/java/com/mapbefine/mapbefine/config/WebMvcConfig.java
WebMvcConfig
기존 Cors 설정에 Location Header에 대한 권한이 빠져 있어서, 추가했습니다.
#113 
closed #113
=> [BE] Cors 권한 추가 설정

.github/workflows/gradle.yml, .github/workflows/merge.yml, .github/workflows/pull-request.yml, backend/build.gradle
workflows (gradle.yml)
change build result name
#120 
issue : #119 
pull-request : #120
=> [BE] Github Action workflows CD refactoring

frontend/src/components/MergeOrSeeTogether/index.tsx, frontend/src/components/PinPreview/index.tsx, frontend/src/components/TopicCard/index.tsx, frontend/src/components/common/Flex/index.ts, frontend/src/components/common/Tag/index.tsx, frontend/src/pages/Home.tsx, frontend/src/pages/SelectedTopic.tsx
토픽 및 핀 병합할 때 태그 추가되는 기능 구현
1. 토픽 및 핀 병합할 때 태그 추가되는 컴포넌트 만들기
2. 토픽 및 핀을 추가할 때 태그가 새로 만들어지는 기능 만들기
close #116
=> [FE] Feature/#116 토픽 및 핀 병합할 때 태그 추가되는 기능 구현

frontend/.env, frontend/src/App.tsx, frontend/src/components/MergeOrSeeTogether/index.tsx, frontend/src/components/PinPreview/index.tsx, frontend/src/components/TopicCard/TopicCard.stories.ts, frontend/src/components/TopicCard/index.tsx, frontend/src/components/TopicInfo/index.tsx, frontend/src/components/common/Flex/index.ts, frontend/src/components/common/Tag/index.tsx, frontend/src/hooks/useNavigator.ts, frontend/src/pages/Home.tsx, frontend/src/pages/NewPin.tsx, frontend/src/pages/NewTopic.tsx, frontend/src/pages/PinDetail.stories.ts, frontend/src/pages/PinDetail.tsx, frontend/src/pages/SelectedTopic.tsx, frontend/src/pages/UpdatedPinDetail.tsx, frontend/src/store/TagId.tsx, frontend/src/store/TopicsId.tsx, frontend/src/types/FormValues.ts, frontend/src/types/Topic.ts, frontend/webpack.common.js
토픽, 핀 병합 및 같이보기 기능 구현
- 토픽 같이보기 기능 구현
- 핀 병합 기능 구현
- 취소하기 기능 구현
- 체크박스 기능 구현
close #129
=> [FE] Feature/#129 토픽, 핀 병합 및 같이보기 기능 구현

frontend/src/components/Map.tsx, frontend/src/components/TopicCard/index.tsx, frontend/src/pages/NewPin.tsx, frontend/src/pages/SelectedTopic.tsx, frontend/src/utils/getAddress.ts
지도 기능과 사이드바 기능 develop으로 merge 후 발생하는 에러 해결
- merge 후 싱크 작업하기
- merge 후 발생하는 에러 해결
close #139
=> [FE]Refactor/#139 머지 후 싱크 및 에러 해결 작업

.github/workflows/fe-merge-dev.yml, .github/workflows/fe-merge-prod.yml
프론트엔드 운영 및 개발 배포를 위한 CD workflow
프론트엔드 main, develop 브랜치에 대한 PR이 merge될 때, 빌드 및 배포를 수행하는 Github Action workflow입니다.
(`frontend/` 내의 파일 변경 사항이 있는 PR인 경우 실행됨)
PR 생성 및 추가 push 시 테스트를 실행하는 CI workflow는 다음 스프린트에 추가 예정입니다.
#119
#120
#122
#135
=> [FE] 프론트엔드 Github Action workflows CD 추가

.github/workflows/fe-merge-dev.yml, .github/workflows/fe-merge-prod.yml
workflows
CI/CD를 위한 workflows 코드 중, 의존성 관련 이슈(npm install --froce)를 해결하기 위해 수정하였습니다.
=> [FE] 프론트 CI/CD workflows 수정

frontend/src/components/TopicCard/index.tsx, frontend/src/components/common/Box/index.ts
토픽 카드 이미지 적용 및 blur처리
- 토픽 카드에 이미지 적용
- 토픽 카드 텍스트 부분에 blur처리
close #147
=> [FE]Refactor/#147 토픽 카드 이미지 적용 및 blur처리

.github/workflows/fe-merge-dev.yml, .github/workflows/fe-merge-prod.yml
workflows
CI/CD를 위한 workflows 코드 중, 의존성 관련 이슈(npm install --froce)를 해결하기 위해 수정하였습니다.
=> [FE] CI/CD workflows 코드 재수정 

frontend/src/components/TopicCard/index.tsx, frontend/src/components/common/Box/index.ts
Reverts woowacourse-teams/2023-map-befine#148
=> Revert "[FE]Refactor/#147 토픽 카드 이미지 적용 및 blur처리"

.github/workflows/fe-merge-dev.yml, .github/workflows/fe-merge-prod.yml
Reverts woowacourse-teams/2023-map-befine#149
=> Revert "[FE] CI/CD workflows 코드 재수정 "

.github/workflows/fe-merge-dev.yml, .github/workflows/fe-merge-prod.yml
프론트엔드 workiflows 코드 수정
working directory 수정
=> [FE] CI/CD workflows 코드 재수정

frontend/package.json, frontend/src/components/TopicCard/index.tsx, frontend/src/components/common/Box/index.ts
토픽 카드 이미지 적용 및 blur처리
- 토픽 카드에 이미지 적용
- 토픽 카드 텍스트 부분에 blur처리
https://github.com/woowacourse-teams/2023-map-befine/pull/148
에서 이미 리뷰 approve 받았습니다!!!
close #147
=> [FE]Refactor/#147 토픽 카드 이미지 적용 및 blur처리 

frontend/package.json, frontend/src/components/TopicCard/index.tsx, frontend/src/components/common/Box/index.ts
Reverts woowacourse-teams/2023-map-befine#163
=> Revert "[FE]Refactor/#147 토픽 카드 이미지 적용 및 blur처리 "

backend/src/main/java/com/mapbefine/mapbefine/config/WebMvcConfig.java
CORS 허용 Origin (WebMvcConfig)
CORS 허용 Origin에 개발서버, 운영서버 도메인 추가
closed #170
=> [BE] CORS 허용 Origin에 개발서버, 운영서버 도메인 추가

backend/src/main/java/com/mapbefine/mapbefine/config/WebMvcConfig.java
CORS 허용 Origin (WebMvcConfig)
CORS 허용 여러 Origin 모두 설정하도록 수정
#171 에 대한 재수정
closed #170
=> [BE] CORS 허용 여러 Origin 모두 설정하도록 수정

frontend/package-lock.json, frontend/public/mockServiceWorker.js, frontend/src/components/Map.tsx, frontend/src/context/MarkerContext.tsx, frontend/src/pages/SelectedTopic.tsx
지도 화면에서 발생하는 버그들을 수정한다.
핀 중복 생성 및 초기 위치로 핀 자동 생성 에러 해결
closed #167
=> [FE]Fix/#167  전반적인 지도 오류 수정 및 개선

frontend/src/components/Layout/index.tsx, frontend/src/components/Map.tsx, frontend/src/components/MergeOrSeeTogether/index.tsx, frontend/src/components/PinPreview/index.tsx, frontend/src/components/Tag/index.tsx, frontend/src/components/TopicCard/index.tsx, frontend/src/components/TopicInfo/index.tsx, frontend/src/components/common/Box/index.ts, frontend/src/const/pinImage.ts, frontend/src/context/MarkerContext.tsx, frontend/src/hooks/useAnimateClickedPin.ts, frontend/src/hooks/useClickedCoordinate.ts, frontend/src/hooks/useFocusToMarkers.ts, frontend/src/hooks/useMapClick.ts, frontend/src/hooks/useUpdateCoordinates.ts, frontend/src/lib/getAddressFromServer.ts, frontend/src/pages/Home.tsx, frontend/src/pages/NewPin.tsx, frontend/src/pages/NewTopic.tsx, frontend/src/pages/PinDetail.tsx, frontend/src/pages/SelectedTopic.tsx, frontend/src/pages/UpdatedPinDetail.tsx, frontend/src/types/index.d.ts
map UI에 관련된 코드 전반적인 리팩토링
- 관심사 분리
- 핀 클릭 시 줌 레벨 변경
- 보여지는 핀 이미지 수정
커스텀 훅으로 분리 및 논의한 방식으로 유저 플로우 수정
closed #186
=> [FE]Refactor/#186 map api 리팩토링

frontend/src/components/Layout/Logo.tsx, frontend/src/components/Layout/index.tsx, frontend/src/components/MergeOrSeeTogether/index.tsx, frontend/src/components/PinPreview/index.tsx, frontend/src/components/TopicCard/index.tsx, frontend/src/components/TopicInfo/index.tsx
웹 접근성 대상 선정 및 개선
- 웹 접근성 대상 선정
- 웹 접근성 개선
close #184
=> [FE]Feature/#184 웹 접근성 대상 선정 및 개선

frontend/src/components/PinPreview/index.tsx, frontend/src/pages/SelectedTopic.tsx
같이 보기에서 핀 클릭 시 같이 보기가 풀리는 오류 수정
#191
=> [FE]FIX/#191 같이 보기에서 핀 클릭 시 같이 보기가 풀리는 오류 수정

frontend/src/components/Layout/index.tsx, frontend/src/hooks/useAnimateClickedPin.ts
지도의 최대 줌 레벨을 고정한다
도메인 정책상 최대 줌 인 레벨을 제한한다.
=> [FE]Refactor/#196 줌 레벨 제한

frontend/src/components/Layout/Logo.tsx, frontend/src/components/PinPreview/index.tsx, frontend/src/components/TopicCard/index.tsx, frontend/src/pages/Home.tsx
=> [FE]Feature/#184 웹 접근성  개선

frontend/public/index.html, frontend/src/components/Layout/index.tsx, frontend/src/context/MarkerContext.tsx, frontend/src/hooks/useAnimateClickedPin.ts, frontend/src/hooks/useClickedCoordinate.ts, frontend/src/hooks/useFocusToMarkers.ts, frontend/src/types/index.d.ts
Tmap 지도 UI에 의해 발생한 문제를 해결함
vector 맵 형식으로 변경한다. 
closed #231 #228 #217
=> [FE]Refactor/#231,#228,#217 전반적인 지도 UI 문제 해결

frontend/src/components/Layout/index.tsx
=> [FE] 머지 과정에서 누락된 import 추가

frontend/src/context/MarkerContext.tsx, frontend/src/hooks/useMapClick.ts, frontend/src/pages/NewPin.tsx
vector 버전 지도로 바꾸어서 생긴 차이점을 수정한다.
마우스 클릭 시 위경도 읽어오는 기능
주소 검색창 중복 출력 문제 해결
마커 선택시 이벤트 적용
closed #248
=> [FE]Refactor/#248 지도 버전 변경 반영

.github/workflows/fe-pull-request.yml
pr을 작성할때마다 테스트를 자동으로 실행하게 한다.
github actions를 이용해서 jest 테스트를 실행하게 스크립트를 작성한다. 
closed #201
=> [FE]Feature/#201 프론트 테스트 자동화

frontend/src/components/Layout/Navbar.tsx, frontend/src/components/common/ShapeImage/index.tsx, frontend/src/components/common/Tooltip/index.tsx
공통적으로 사용될 툴팁과 이미지를 재사용가능한 컴포넌트로 구현한다.
모양, 크기 조정이 가능한 이미지 컴포넌트를 구현한다.
범용성있는 툴팁 컴포넌트를 구현해 사용한다.
closed #266
=> [FE] feature/#266 이미지, 툴팁 공통 컴포넌트 구현

frontend/src/pages/AskLoginPage.tsx, frontend/src/pages/KaKaoRedirectPage.tsx
로그인 url 변경
로그인 url 변경
#283 
closed #283
=> [FE] fix/#283 소셜 로그인 url 변경

frontend/src/pages/AskLoginPage.tsx, frontend/src/pages/KaKaoRedirectPage.tsx, frontend/src/pages/My.tsx, frontend/src/router.tsx
=> hotfix: https로 수정

frontend/src/pages/KaKaoRedirectPage.tsx
redirect url 변경
redirect url 변경
=> hotfix: redirect url 변경

frontend/src/pages/KaKaoRedirectPage.tsx
=> hotfix: function-async

frontend/src/pages/KaKaoRedirectPage.tsx
=> hotfix: routepage 제거

frontend/src/apis/getApi.ts
=> fix: 데이터 로그 확인

frontend/src/pages/KaKaoRedirectPage.tsx
=> hotfix: url에 api 추가

frontend/src/pages/KaKaoRedirectPage.tsx
=> hotfix: data-shape

frontend/src/apis/getApi.ts
=> fix : seperate login

frontend/src/apis/getApi.ts, frontend/src/pages/KaKaoRedirectPage.tsx
=> fix: login-error

frontend/src/components/PinsOfTopic/index.tsx
=> [FE] 머지 충돌 해결 시 누락된 부분 보완

backend/src/docs/asciidoc/bookmark.adoc, backend/src/main/java/com/mapbefine/mapbefine/auth/infrastructure/BearerAuthorizationExtractor.java, backend/src/main/resources/application.yml, backend/src/test/java/com/mapbefine/mapbefine/common/TestAuthHeaderProvider.java, backend/src/test/java/com/mapbefine/mapbefine/location/presentation/LocationControllerTest.java, backend/src/test/java/com/mapbefine/mapbefine/oauth/presentation/OauthControllerTest.java
인증 인가 관련 코드
- 작은 변경사항이라 이슈 발행 생략합니다..ㅎㅎ
- 액세스 토큰 요청 및 응답 형식 통일
- RestDocs 수정
- 로그인 응답 시에는 토큰 값만 반환합니다.
- 요청 시에는 헤더에 Bearer를 붙인 값을 보내주셔야 합니다.
=> [BE] refactor 인증 인가 관련 수정

frontend/src/components/BookmarksContainer/BookmarksList/index.tsx, frontend/src/components/BookmarksContainer/index.tsx, frontend/src/components/TopicCard/index.tsx, frontend/src/pages/Bookmark.tsx, frontend/src/pages/BookmarksPage.tsx, frontend/src/router.tsx, frontend/src/types/Bookmarks.ts
즐겨찾기 페이지 구현
즐겨찾기 페이지 UI 구현
get api 적용
close #300
=> [FE] feature/#300 즐겨찾기 페이지 구현

frontend/src/components/Modal/index.tsx, frontend/src/components/ModalMyTopicList/index.tsx, frontend/src/components/ModalTopicCard/index.tsx, frontend/src/pages/NewPin.tsx, frontend/src/pages/PinDetail.tsx, frontend/src/types/Topic.ts
내 지도 토픽 목록 list 컴포넌트 구현 및 모달 창에 적용
내가 만든 지도 목록 모달에 띄울 컴포넌트 만들기
get api 요청
close #302
=> [FE] feature/#302 내가 만든 지도 목록 모달에 띄우기

frontend/src/router.tsx
=> refactor: 리다이렉트 페이지 라우트

frontend/src/apis/postApi.ts, frontend/src/components/Layout/index.tsx, frontend/src/components/ModalMyTopicList/addToMyTopicList.tsx, frontend/src/components/ModalMyTopicList/index.tsx, frontend/src/components/ModalTopicCard/index.tsx, frontend/src/hooks/useUpdateCoordinates.ts, frontend/src/pages/NewPin.tsx, frontend/src/pages/NewTopic.tsx, frontend/src/pages/PinDetail.tsx
권한이 있는 토픽을 선택하는 기능 구현
- 메인화면에서 핀을 추가할때 권한이 있는 토픽을 선택할 수 있게 한다
- 다른사람의 지도에서 특정 핀을 내 토픽에 추가할 수 있게 한다
#331 
closed #331
=> [FE] feature/#331 권한있는 토픽 접근 가능 기능 구현

frontend/src/components/TopicListContainer/index.tsx
=> fix: 오류 수정

backend/.gitignore, backend/src/main/java/com/mapbefine/mapbefine/common/GlobalExceptionHandler.java, backend/src/main/java/com/mapbefine/mapbefine/common/config/TimeZoneConfig.java, backend/src/main/java/com/mapbefine/mapbefine/common/entity/Image.java, backend/src/main/java/com/mapbefine/mapbefine/common/interceptor/AuthInterceptor.java, backend/src/main/resources/application-dev.yml, backend/src/main/resources/application-prod.yml, backend/src/main/resources/application.yml, backend/src/main/resources/logback-spring.xml, backend/src/test/java/com/mapbefine/mapbefine/common/entity/ImageTest.java, backend/src/test/resources/application.yml, backend/src/test/resources/logback-test.xml
#330 참고부탁드립니다.
#330 참고부탁드립니다.
에러 해결을 위한 일부 fix 커밋이 존재합니다.
closed #330
=> [BE] feature/#330 로깅 적용

frontend/package.json, frontend/src/components/TopicInfo/index.tsx, frontend/src/pages/NewPin.tsx, frontend/src/pages/PinDetail.tsx
=> [FE] Fix/all

frontend/src/apis/putApi.ts, frontend/src/components/AddFavorite/index.tsx, frontend/src/components/AddSeeTogether/index.tsx, frontend/src/pages/Bookmark.tsx, frontend/src/pages/KaKaoRedirectPage.tsx, frontend/src/pages/SeeTogetherTopics.tsx, frontend/src/pages/UpdatedPinDetail.tsx
=> [FE] Fix/chore-things

frontend/src/pages/KaKaoRedirectPage.tsx
=> [FE] fix: 로그인 후 새로고침 로직 수정

backend/src/main/java/com/mapbefine/mapbefine/atlas/exception/AtlasErrorCode.java, backend/src/main/java/com/mapbefine/mapbefine/atlas/exception/AtlasException.java, backend/src/main/java/com/mapbefine/mapbefine/bookmark/application/BookmarkCommandService.java, backend/src/main/java/com/mapbefine/mapbefine/bookmark/exception/BookmarkException.java, backend/src/main/java/com/mapbefine/mapbefine/common/GlobalExceptionHandler.java, backend/src/main/java/com/mapbefine/mapbefine/common/exception/BadRequestException.java, backend/src/main/java/com/mapbefine/mapbefine/common/exception/ConflictException.java, backend/src/main/java/com/mapbefine/mapbefine/common/exception/ErrorCode.java, backend/src/main/java/com/mapbefine/mapbefine/common/exception/ForbiddenException.java, backend/src/main/java/com/mapbefine/mapbefine/common/exception/GlobalException.java, backend/src/main/java/com/mapbefine/mapbefine/common/exception/NotFoundException.java, backend/src/main/java/com/mapbefine/mapbefine/common/exception/UnauthorizedException.java, backend/src/main/java/com/mapbefine/mapbefine/common/exception/dto/ErrorResponse.java, backend/src/main/java/com/mapbefine/mapbefine/location/exception/LocationException.java, backend/src/main/java/com/mapbefine/mapbefine/member/application/MemberQueryService.java, backend/src/main/java/com/mapbefine/mapbefine/member/exception/MemberException.java, backend/src/main/java/com/mapbefine/mapbefine/oauth/domain/AuthCodeRequestUrlProviderComposite.java, backend/src/main/java/com/mapbefine/mapbefine/oauth/domain/OauthMemberClientComposite.java, backend/src/main/java/com/mapbefine/mapbefine/oauth/exception/OathException.java, backend/src/main/java/com/mapbefine/mapbefine/permission/application/PermissionCommandService.java, backend/src/main/java/com/mapbefine/mapbefine/permission/application/PermissionQueryService.java, backend/src/main/java/com/mapbefine/mapbefine/permission/exception/PermissionException.java, backend/src/main/java/com/mapbefine/mapbefine/pin/application/PinQueryService.java, backend/src/main/java/com/mapbefine/mapbefine/pin/exception/PinException.java, backend/src/main/java/com/mapbefine/mapbefine/topic/application/TopicQueryService.java, backend/src/main/java/com/mapbefine/mapbefine/topic/exception/TopicException.java
- 로깅용 어떤 대상의 ID에서 해당 오류가 발생했는지 확인하기 위해 ID값 보여주기
closed #338
=> [BE] refactor/#388 ErrorCode 내 Info 추가

frontend/src/components/Layout/Navbar.tsx, frontend/src/components/MyInfoContainer/MyInfoList/index.tsx, frontend/src/pages/LoginError.tsx, frontend/src/pages/NewPin.tsx, frontend/src/pages/NewTopic.tsx, frontend/src/pages/PinDetail.tsx
에러 토스트 메시지 변경 및 스크롤 에러 수정
에러 토스트 메시지 변경 및 스크롤 에러 수정
=> [FE] refactor: 에러 토스트 메시지 변경 및 스크롤 에러 수정

frontend/src/components/ModalMyTopicList/addToMyTopicList.tsx, frontend/src/components/ModalMyTopicList/index.tsx, frontend/src/components/ModalTopicCard/index.tsx, frontend/src/pages/NewTopic.tsx
=> [FE] refactor: 에러 메시지 및 에러 해결

.github/workflows/fe-pull-request.yml, frontend/cypress/e2e/mapbefine.cy.ts
cypress test 추가 및 자동 배포 적용
cypress test 추가 및 자동 배포 적용
=> [FE] cypress test 추가 및 자동 배포 적용

.github/workflows/fe-pull-request.yml
cypress 자동 배포 설정
cypress 자동 배포 설정
=> [FE] test: cypress 자동 배포 설정

.github/workflows/fe-pull-request.yml
cypress 테스트 자동화
cypress 테스트 자동화
=> [FE] test: cypress 테스트 자동화

.github/workflows/fe-pull-request.yml
=> [FE] test: 사이프레스 자동화

.github/workflows/fe-merge-dev.yml, .github/workflows/fe-merge-prod.yml, frontend/.gitignore, frontend/package-lock.json, frontend/package.json, frontend/src/apis/getApi.ts, frontend/src/apis/postApi.ts, frontend/src/apis/putApi.ts, frontend/webpack.common.js
=> hotfix: api 분리

.github/workflows/fe-merge-dev.yml, .github/workflows/fe-merge-prod.yml, frontend/src/pages/KaKaoRedirectPage.tsx
api response 변경
api response 변경
=> [FE] Hotfix:api response 변경

frontend/src/pages/Home.tsx
refactor: 홈 화면 컨테이너 위치 및 명 변경
refactor: 홈 화면 컨테이너 위치 및 명 변경
=> [FE] refactor: 홈 화면 컨테이너 위치 및 명 변경

frontend/package.json, frontend/src/components/ModalMyTopicList/addToMyTopicList.tsx, frontend/src/components/ModalMyTopicList/index.tsx, frontend/src/components/ModalTopicCard/index.tsx, frontend/src/pages/KaKaoRedirectPage.tsx, frontend/src/pages/NewPin.tsx, frontend/src/pages/PinDetail.tsx
Hotfix/design 디자인 오류 수정
Hotfix/design 디자인 오류 수정
=> [FE] Hotfix/design 디자인 오류 수정

.github/workflows/be-merge-dev.yml, .github/workflows/be-pull-request.yml, backend/src/main/resources/application-dev.yml, backend/src/main/resources/application-prod.yml, backend/src/main/resources/application.yml, backend/src/main/resources/logback-spring.xml, backend/src/test/resources/application.yml, backend/src/test/resources/logback-spring.xml, backend/src/test/resources/logback-test.xml
테스트 로그 설정 파일
프로덕션 로그 설정 파일
#366 참조 부탁드립니다.
- 오류 해결 : 기존 테스트 로그 설정 파일에 로그 패턴 경로가 잘못된 부분을 수정했습니다.
- 로그 설정 보완 : 로그 출력 내용에 스레드, PID, 레벨, 로거를 추가하고 콘솔 로그의 경우 색상을 적용했습니다.
- 테스트 로그 레벨 설정 : 프로젝트 패키지 내의 로그만 DEBUG 레벨로, 나머지는 INFO 레벨로 출력하도록 설정했습니다. (단, JPA 로그는 yaml 파일의 설정을 따르므로, 파라미터 바인딩을 TRACE 레벨로 출력합니다.)
GitHub Actions에서도 수정 내용이 잘 반영되었는지 확인하고자, develop 브랜치 분리에 따른 워크플로우 수정을 함께 PR에 올립니다.
closed #366 
https://breakcoding.tistory.com/400
https://lovethefeel.tistory.com/88
https://www.baeldung.com/spring-boot-logback-log4j2
=> [BE] Fix/#366 테스트 수행 시 로그 패턴 깨지는 오류 해결

backend/src/test/java/com/mapbefine/mapbefine/DatabaseCleanup.java
DatabaseCleanUp
DatabaseCleanUp에서 사용중이던 EntityManager를 JdbcTemplate으로 변경하였습니다.
closed #370
=> [BE] Refactor/#370 DatabaseCleanup JdbcTemplate 적용

frontend/src/pages/AskLogin.tsx
solve login error
solve login error
=> [FE] Hotfix/solve login error

.github/workflows/be-merge-dev.yml, .github/workflows/be-merge-prod.yml, .github/workflows/be-pull-request.yml
백엔드 workflow 파일
빌드 시 서브모듈을 불러오도록 수정
=> [BE] Hotfix/#380-2 서브모듈 불러오도록 워크플로우 수정

backend/src/main/resources/logback-spring.xml
=> [BE] Hotfix/#380-3 서브모듈 불러오도록 워크플로우 수정 확인용 PR

backend/src/main/java/com/mapbefine/mapbefine/common/config/S3Config.java, backend/src/main/java/com/mapbefine/mapbefine/topic/presentation/TopicController.java
S3 를 통한 Image 업로드
S3 를 연동하여 Image 를 파일로 올릴 수 있도록 구현
=> [BE] S3 를 통한 Image Upload 기능 추가 테스트

backend/src/main/resources/logback-spring.xml
로그 설정 파일
- Info, Debug 레벨 커스텀 로그만 출력하도록 변경 (패키지 범위를 com.mapbefine.mapbefine 으로 지정)
- JPA 쿼리만 저장하고, 파라미터 바인딩 저장은 불필요해보여서 삭제했습니다.
#376
=> [BE] Hotfix/log Info, Debug 레벨 커스텀 로그만 출력하도록 변경

backend/src/main/java/com/mapbefine/mapbefine/pin/application/PinCommandService.java, backend/src/main/java/com/mapbefine/mapbefine/pin/presentation/PinController.java, backend/src/main/java/com/mapbefine/mapbefine/s3/application/S3ServiceImpl.java, backend/src/main/java/com/mapbefine/mapbefine/s3/domain/UploadFile.java, backend/src/test/java/com/mapbefine/mapbefine/pin/PinIntegrationTest.java, backend/src/test/java/com/mapbefine/mapbefine/pin/application/PinCommandServiceTest.java, backend/src/test/java/com/mapbefine/mapbefine/pin/presentation/PinControllerTest.java
Image Upload 기능
Pin 생성 시 Image 를 한꺼번에 Upload 할 수 있도록 로직 수정
=> [BE] feat/#386 Pin 생성 시 Image Upload 테스트

backend/src/main/java/com/mapbefine/mapbefine/auth/infrastructure/JwtTokenProvider.java, backend/src/main/java/com/mapbefine/mapbefine/common/config/WebConfig.java
=> [BE] Fix/#424 refresh token duplicated

backend/src/main/java/com/mapbefine/mapbefine/auth/application/TokenService.java, backend/src/main/java/com/mapbefine/mapbefine/auth/domain/token/RefreshTokenRepository.java, backend/src/main/java/com/mapbefine/mapbefine/auth/infrastructure/JwtTokenProvider.java, backend/src/main/java/com/mapbefine/mapbefine/auth/presentation/LoginController.java, backend/src/main/java/com/mapbefine/mapbefine/common/config/WebConfig.java
- delete 메서드에 clearAutomatically 속성 적용
=> [BE] HotFix/#426 delete 메서드에 clearAutomatically 속성 적용

backend/src/main/java/com/mapbefine/mapbefine/auth/application/TokenService.java, backend/src/main/java/com/mapbefine/mapbefine/auth/domain/token/RefreshTokenRepository.java, backend/src/main/java/com/mapbefine/mapbefine/auth/infrastructure/JwtTokenProvider.java, backend/src/main/java/com/mapbefine/mapbefine/auth/presentation/LoginController.java, backend/src/main/java/com/mapbefine/mapbefine/common/config/WebConfig.java
=> [BE] HotFix/#426 tokenService flush 추가

frontend/src/apis/getApi.ts
=> [hotfix] refreshToken을 재요청할때 body에 accessToken을 추가

frontend/src/apis/getApi.ts
=> [hotfix] getAPI 헤더에 content-type 추가

backend/src/main/java/com/mapbefine/mapbefine/auth/exception/AuthErrorCode.java, backend/src/main/java/com/mapbefine/mapbefine/auth/infrastructure/JwtTokenProvider.java, backend/src/main/java/com/mapbefine/mapbefine/auth/presentation/LoginController.java, backend/src/main/java/com/mapbefine/mapbefine/common/config/WebConfig.java
=> [BE] HotFix/#424 refresh token duplicated

frontend/src/apis/getApi.ts
=> refactor: localstorage userToken getItem요청 수정

frontend/src/apis/getApi.ts
=> hotfix: 재발급시 받은 데이터 저장 로직 수정

frontend/src/apis/getApi.ts
=> hotfix: abortController 적용

frontend/src/apis/getApi.ts
=> hotfix: abortController 여러개 적용

frontend/src/apis/getApi.ts
=> fix: refresh token 요청 중 재요청 차단

frontend/src/apis/getApi.ts
=> fix: abort 컨트롤러 예외 처리 수정

frontend/src/apis/getApi.ts
=> fix: response 타입 동일화

frontend/src/apis/getApi.ts
=> fix: refresh response console 체크

backend/src/main/java/com/mapbefine/mapbefine/common/config/WebConfig.java
- cors credential 설정 추가
cors allowCredentials 설정 추가
=> [BE]Hotfix/cors allowCredentials 설정 추가

frontend/src/apis/getApi.ts
=> fix: console.log 추가

frontend/src/apis/getApi.ts
=> fix: console.log response 부분 추가

frontend/src/apis/getApi.ts
=> fix: response clone 하여 오류 수정

backend/src/main/java/com/mapbefine/mapbefine/common/config/WebConfig.java
=> [BE] Hotfix/cors allowHeaders 와일드카드 적용

backend/src/main/java/com/mapbefine/mapbefine/common/config/S3Config.java, backend/src/main/java/com/mapbefine/mapbefine/oauth/domain/kakao/KakaoAuthCodeRequestUrlProvider.java
Tomcat 설정
Tomcat 설정 변경
Tomcat 설정 로그 출력
현재 Tomcat 설정 및 redirect uri 를 확인하기 위해서 log.debug 를 S3Config, KakaoAuthCodeRequestUrlProvider 에다가 추가해놓은 상태입니다!
부하테스트가 끝나면 지울 예정입니다.
=> [BE] 부하테스트를 위한 Tomcat Log 추가

frontend/src/components/MyInfo/index.tsx
=> hotfix: 로그아웃 post 데이터 타입 변경

frontend/package-lock.json, frontend/package.json
=> [FE] hotfix: browser-image-compression 패키지 제이슨 누락 수정

frontend/src/components/Layout/NavbarItem.tsx
=> hotfix: 모아보기 누락 로직 추가

frontend/src/apis/deleteApi.ts, frontend/src/apis/getApi.ts, frontend/src/apis/postApi.ts, frontend/src/apis/putApi.ts, frontend/src/apis/utils.ts
권한이 필요한 모든 api요청에 대해 만료된 토큰을 재발급 할 수 있도록 구현
put, post, api에 대해 refresh토큰을 재발급 받는 로직을 적용한다.
#466 
closed #466
=> [FE] 토큰 재발급 로직 모든 메소드에 적용 

frontend/src/components/AuthorityRadioContainer/index.tsx, frontend/src/components/Layout/Navbar.tsx, frontend/src/components/Modal/index.tsx, frontend/src/components/TopicInfo/UpdatedTopicInfo.tsx, frontend/src/pages/NewPin.tsx, frontend/src/pages/NewTopic.tsx
토픽 생성 및 수정 시 권한 설정 컴포넌트 및 네브바
* 토픽 생성 시 GROUP_ONLY 특정인원 설정 로직에서 비공개 지도일 때 특정인원 설정이 안 되는 오류를 수정한다.
* 토픽 수정 시 GROUP_ONLY 에서 ALL_MEMBERS 로 전환되는 과정에서 권한을 부여한 특정인원 리스트를 삭제하지 않는 오류를 수정한다.
* 추가하기 모달 태블릿, 모바일 환경에서 가운데 정렬
close #472
=> [FE] Fix/#472 토픽 수정 시 권한 수정 보류

frontend/src/router.tsx
Hotfix 동적 임포트에 suspense 적용
Hotfix 동적 임포트에 suspense 적용
=> [FE] Hotfix 동적 임포트에 suspense 적용

frontend/src/components/Layout/Navbar.tsx
=> fix: merge 과정 중 충돌 해결 오류 수정

frontend/src/apiHooks/usePost.ts, frontend/src/apis/postApi.ts, frontend/src/components/Modal/index.tsx, frontend/src/components/ModalMyTopicList/addToMyTopicList.tsx, frontend/src/components/PinImageContainer/index.tsx
개발 서버 QA 후 발생한 이슈 해결
close #481
=> [FE] Refactor/#481 개발 서버 QA 후 발생한 이슈 해결

frontend/src/components/common/Text/index.ts
개행 처리 속성 적용한 곳에서 wrap 속성이 적용되지 않아 가로 스크롤이 생기는 오류 수정
https://developer.mozilla.org/ko/docs/Web/CSS/white-space
=> [FE] 개행 처리 적용 시 wrap 속성이 적용되지 않던 오류 수정

frontend/src/App.tsx, frontend/src/router.tsx
=> [FE] Refactor/495 GA 위치 변경

frontend/public/index.html
=> [FE] feat: GA 추가

frontend/src/App.tsx
Google Analytics 불필요한 코드 삭제 및 최종본
Google Analytics 불필요한 코드 삭제 및 최종본
close #495
=> [FE] refactor/#495 Google Analytics 불필요한 코드 삭제 및 최종본

.github/workflows/fe-merge-dev.yml, .github/workflows/fe-merge-prod.yml
=> hotfix: 환경변수 수정

backend/src/main/java/com/mapbefine/mapbefine/topic/domain/Topic.java
Set 구현체 변경
Set 구현체를 LinkedHashSet 으로 변경
=> [BE] 토픽 목록의 순서를 유지하기 위한 자료 구조 변경

backend/src/main/java/com/mapbefine/mapbefine/topic/domain/Topic.java
Set 구현체 변경
Set 구현체를 LinkedHashSet 으로 변경
=> [BE] 기존의 HashSet 을 LinkedHashSet 으로 변경

frontend/src/components/Layout/Navbar.tsx, frontend/src/components/Layout/index.tsx, frontend/src/components/Map/index.tsx, frontend/src/components/Modal/index.tsx, frontend/src/constants/index.ts, frontend/src/pages/AskLogin.tsx, frontend/src/pages/Home.tsx, frontend/src/pages/KakaoRedirect.tsx, frontend/src/pages/NotFound.tsx, frontend/src/pages/PinDetail.tsx
* 브라우저 별마다 URL 주소창 처리 방식 및 높이가 달라 NavBar가 가리는 오류를 수정한다.
* API env를 적용하여 개발서버와 운영서버를 분리한다.
close #526 
https://yohanpro.com/posts/css/%EB%B8%8C%EB%9D%BC%EC%9A%B0%EC%A0%80-%EC%A3%BC%EC%86%8C%EC%B0%BD-%ED%81%AC%EA%B8%B0-%EC%A0%9C%EC%96%B4
=> [FE] Refactor/#526 반응형 네브바 가림 문제 해결

frontend/public/index.html
=> [FE] hotfix 운영서버 GA 코드 심기

frontend/src/components/Layout/Navbar.tsx, frontend/src/components/Layout/index.tsx, frontend/src/components/Map/index.tsx, frontend/src/components/Modal/index.tsx, frontend/src/constants/index.ts, frontend/src/pages/PinDetail.tsx, frontend/src/types/tmap.d.ts
제발 좀 되라;;;;;;;;;;;;; 
* Layout 컴포넌트 반응형 height 옵션 수정
* 지도 scaleBar 제거
* Layout 컴포넌트 반응형 height 옵션 수정
* 지도 scaleBar 제거
정확한 원인 파악이 안 됩니다.. 날 잡고 CSS 로직 갈아 치워야할듯요.
=> [FE] Hotfix/navbar 모바일 스크롤 여백으로 인한 네브바 하단 고정 오류 수정

frontend/src/components/AuthorityRadioContainer/index.tsx
* 비회원자에게 members 목록 보여주지 않도록 변경
긴급사항으로 머지하겠습니다.
=> [FE] hotfix: 비회원자에게 members 목록 보여주지 않도록 변경

frontend/src/pages/PinDetail.tsx
비로그인 시 pin image button 숨기기
비로그인 시 pin image button 숨기기
현재 main에서 분기하든 develop-FE로 분기하든 백엔드 commit이 딸려옵니다~!! 이거 괜찮은거 맞을까요?!!~!
close #541
=> [FE] Refactor/#541 비로그인 시 pin image button 숨기기

frontend/webpack.common.js
=> hotfix: dotenv 추가

.github/workflows/fe-merge-dev.yml, frontend/src/apis/getPoiApi.ts
hotfix env 이름 형식 통일
hotfix env 이름 형식 통일
=> [FE] hotfix env 이름 형식 통일

frontend/webpack.common.js
=> hotfix: DotenvWebpackPlugin추가

frontend/webpack.common.js
=> fix: require 수정

.github/workflows/be-merge-dev.yml, .github/workflows/be-merge-prod.yml
github workflow
github workflow 에 cd 구문 추가
=> [BE] Env/#545 무중단 배포를 위한 구성 파일 작성 

backend/src/main/java/com/mapbefine/mapbefine/admin/presentation/AdminController.java
adminController
adminController 개행 삭제
=> [BE] env/#545 CI/CD 동작을 위한 개행 삭제

backend/src/docs/asciidoc/topic.adoc, backend/src/main/java/com/mapbefine/mapbefine/topic/application/TopicCommandService.java, backend/src/main/java/com/mapbefine/mapbefine/topic/domain/Topic.java, backend/src/main/java/com/mapbefine/mapbefine/topic/dto/request/TopicUpdateRequest.java, backend/src/main/java/com/mapbefine/mapbefine/topic/presentation/TopicController.java, backend/src/test/java/com/mapbefine/mapbefine/admin/application/AdminCommandServiceTest.java, backend/src/test/java/com/mapbefine/mapbefine/image/FileFixture.java, backend/src/test/java/com/mapbefine/mapbefine/topic/TopicFixture.java, backend/src/test/java/com/mapbefine/mapbefine/topic/TopicIntegrationTest.java, backend/src/test/java/com/mapbefine/mapbefine/topic/application/TopicCommandServiceTest.java, backend/src/test/java/com/mapbefine/mapbefine/topic/domain/TopicTest.java, backend/src/test/java/com/mapbefine/mapbefine/topic/presentation/TopicControllerTest.java
Topic 이미지 수정
Topic 이미지 수정 API 를 구현하였습니다.
작업을 새벽에 진행한다는 특성으로 인해, 코드리뷰를 빠르게 받을 수가 없기에, 미리 모두에게 말씀드렸듯이 바로 Merge 하도록 하겠습니다.
=> [BE] feat: 토픽 이미지 수정 기능 구현

frontend/src/assets/currentLocationBtn.svg, frontend/src/components/Map/index.tsx, frontend/src/hooks/useGeolocation.ts, frontend/src/pages/SelectedTopic.tsx, frontend/src/store/mapInstance.ts, frontend/src/types/tmap.d.ts
* 지도를 대상으로 작업을 진행합니다.
* 가능하면 Zustand로 지도 상태관리를 마이그레이션 합니다.
* infowindow 는 현재위치 기능 구현으로 우선순위에서 미룹니다.
close #578
=> [FE] Refactor/#578 지도 핀 Boundary 조정

frontend/src/components/Map/index.tsx, frontend/src/hooks/useGeolocation.ts
* watchPosition 에서 getCurrent 방식으로 변경
=> refactor: watchPosition 에서 getCurrentPosition으로 변경

backend/Dockerfile-prod
개행 추가
Dockerfile-prod 파일에 공백 추가했습니다.
=> [BE] CI/CD 재 가동을 위한 공백 추가

.github/workflows/be-merge-prod.yml
workflow 수정
이관에 참여한 인원이 전원 동의하였으니, 머지하도록 하겠습니다.
=> [BE] workflow 수정

backend/Dockerfile-dev
=> [BE] CI/CD 구동을 위한 공백추가

frontend/package-lock.json, frontend/package.json
=> chore: reactQuery, Axios 추가
